export const LEGAL_DISCLAIMER =
  "DISCLAIMER: This information is generated by an AI system and is provided for general informational purposes only. " +
  "It does not constitute legal advice and should not be relied upon as such. " +
  "For specific legal concerns, please consult a licensed Philippine attorney. " +
  "Bayanihan.AI is not a law firm and does not provide legal representation.";

export const NOTARIAL_DISCLAIMER =
  "This digital notarial register is a convenience tool for tracking notarial acts. " +
  "The official notarial register must comply with the 2004 Rules on Notarial Practice (A.M. No. 02-8-13-SC). " +
  "Notaries are responsible for verifying accuracy and compliance with all applicable rules.";

export const AI_TRANSPARENCY_NOTICE =
  "This response was generated using artificial intelligence (AI) technology. " +
  "In compliance with NPC Advisory 2024-04, we disclose that AI systems are used to analyze legal texts " +
  "and generate responses. Human oversight is maintained for all automated decision processes.";

export const CITIZEN_NAVIGATOR_DISCLAIMER =
  "This legal navigator provides general legal information to help you understand your rights. " +
  "It is NOT legal advice. For your specific situation, please consult a lawyer. " +
  "Free legal assistance is available through the Public Attorney's Office (PAO) " +
  "and Integrated Bar of the Philippines (IBP) legal aid programs.";
