import { Router, Request, Response } from "express";
import { z } from "zod";

export const researchRouter = Router();

const researchQuerySchema = z.object({
  query: z.string().min(3).max(2000),
  filters: z
    .object({
      court: z.array(z.string()).optional(),
      dateFrom: z.string().optional(),
      dateTo: z.string().optional(),
      caseType: z.array(z.string()).optional(),
    })
    .optional(),
});

researchRouter.post("/", async (req: Request, res: Response) => {
  const parsed = researchQuerySchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({
      success: false,
      error: {
        code: "VALIDATION_ERROR",
        message: "Invalid request body",
        details: parsed.error.flatten(),
      },
    });
    return;
  }

  try {
    // TODO: Forward to ai-engine service
    // const aiResponse = await fetch('http://ai-engine.railway.internal:8000/research', { ... });

    res.json({
      success: true,
      data: {
        answer:
          "This is a placeholder response. The AI engine is not yet connected. " +
          "When operational, this will return AI-generated legal research with cited Philippine case law.",
        citations: [],
        confidenceScore: 0,
        disclaimer:
          "DISCLAIMER: This information is generated by an AI system and is provided for general informational purposes only. " +
          "It does not constitute legal advice. Please consult a licensed Philippine attorney.",
        cached: false,
        latencyMs: 0,
      },
    });
  } catch (error) {
    res.status(502).json({
      success: false,
      error: {
        code: "AI_ENGINE_ERROR",
        message: "Failed to process research query",
      },
    });
  }
});
